run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - github.com/jmoiron/sqlx
          - errors
          - io
          - fmt
          - os
          - strings
          - sync
          - context
          - net/http
          - syscall
          - time
          - net
          - flag
          - bytes
          - testing
          - path/filepath
          - github.com/cronnoss/avitotech/internal/logger
          - github.com/cronnoss/avitotech/internal/server
          - github.com/cronnoss/avitotech/internal/storage
          - github.com/cronnoss/avitotech/internal/storage/sql
          - github.com/cronnoss/avitotech/internal/app
          - github.com/cronnoss/avitotech/internal/model
          - golang.org/x/sync/errgroup
          - github.com/BurntSushi/toml
          - encoding/json
          - github.com/jackc/pgx/stdlib
          - github.com/shopspring/decimal
          - github.com/stretchr/testify/require
          - database/sql

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
    - path: internal/model/balance\.go
      linters:
        - tagliatelle
    - path: internal/model/transaction\.go
      linters:
        - tagliatelle
    - path: internal/model/transfer\.go
      linters:
        - tagliatelle
    - path: internal/app/avitotech\.go
      linters:
        - tagliatelle

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace